version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/app

  restore_deps_cache: &restore_deps_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

  save_deps_cache: &save_deps_cache
    save_cache:
      key: v1-dependencies-{{ checksum "package.json" }}
      paths:
        - node_modules

  install_deps: &install_deps
    run:
      name: Dependencies
      command: npm install && npm run bootstrap

jobs:
  test:
    <<: *container_config
    steps:
      - checkout
      - *restore_deps_cache
      - *install_deps
      - *save_deps_cache
      -
        run:
          name: ESLint
          command: npm run lint
      -
        run:
          name: Jest suite
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      -
        store_test_results:
          path: packages/head-up/reports
      -
        store_artifacts:
          path: packages/head-up/coverage
  deploy:
    <<: *container_config
    steps:
      - checkout
      - *restore_deps_cache
      - *install_deps
      - *save_deps_cache
      - run:
            name: Build packages
            command: npm run build
      -
        run:
          name: Deploy to now.sh
          command: npx now -t ${NOW_TOKEN} && npx now alias -t ${NOW_TOKEN}

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
